/* c/scheme48write-barrier.h.  Generated by configure.  */
/* Copyright (c) 1993-2005 by Richard Kelsey and Jonathan Rees.
   See file COPYING. */

/*
 * We repeat this so we won't have to install sysdep.h.
 */

/* Define if building with BIBOP GC. */
#define S48_GC_BIBOP 1

/* Define if building with two-space GC. */
/* #undef S48_GC_TWOSPACE */

#if defined(S48_GC_BIBOP)
#include "scheme48write-barrier-bibop.h"
#elif defined(S48_GC_TWOSPACE)
#include "scheme48write-barrier-twospace.h"
#endif
